---
- hosts: all
  gather_facts: yes

  tasks:  
    - name: "Check if NGINX is installed"
      package_facts:
        manager: "auto"

    - name: "log4j test result"
      debug: 
        msg: "log4j found"
      when: "'log4j' in ansible_facts.packages"

    - name: "log4j test result"
      debug: 
        msg: "log4j NOT found"
      when: "'log4j' not in ansible_facts.packages"
